name: Kernel_Dynamic_Pulse
on: [push]
jobs:
  tele_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: üñºÔ∏è Pulse Visual
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          photo: logokernel.jpeg
      - name: üìü Pulse Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ‚îÄ‚îÄ‚îÄ [ KERNEL_UPDATE ] ‚îÄ‚îÄ‚îÄ
            LOG: ${{ github.event.head_commit.message }}
            OPERATORE: ${{ github.actor }}
            STATO: SINCRONIZZATO
