- uses: appleboy/telegram-action@v1.0.0
  with:
    to: ${{ secrets.TELEGRAM_CHAT_ID }}
    token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    document: logokernel.jpeg
    caption: |
      ----[ KERNEL_NODE_0 ]----
      AUTHENTICATION: GRANTED
      STATUS: ONLINE

      Benvenuto nel cuore del sistema.
      Sincronizzazione completata.
    parse_mode: ""