name: Kernel_Dynamic_Pulse
on: [push]

jobs:
  tele_sync:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›°ï¸ Sync Repository
        uses: actions/checkout@v3

      - name: ğŸ–¼ï¸ Pulse Visual
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          photo: logokernel.jpeg

      - name: ğŸ“Ÿ Pulse Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            â”€â”€â”€ [ KERNEL_UPDATE ] â”€â”€â”€
            
            LOG: ${{ github.event.head_commit.message }}
            
            OPERATORE: ${{ github.actor }}
            STATO: SINCRONIZZATO
