name: Kernel_Visual_Pulse
on: [push]

jobs:
  tele_sync:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›°ï¸ Sync Repository
        uses: actions/checkout@v3

      - name: ðŸ–¼ï¸ Pulse Visual
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          photo: logokernel.jpeg

      - name: ðŸ“Ÿ Pulse Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *KERNEL NODE 0 - ONLINE*
            `================================`
            
            *Benvenuto nel sistema, operatore.*
            Il nodo Ã¨ stato avviato correttamente.
            
            > Stato: **ATTIVO**
            > Protocollo: **INIZIALIZZATO**
            
            _In attesa di ulteriori istruzioni._
