name: Kernel_Pulse
on: [push]
jobs:
  tele_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/telegram-action@master
        with:
to:$. {{ secrets.TELEGRAM_CHAT_ID }}
token:${{ secrets.TELEGRAM_BOT_TOKEN }}
          photo: logokernel.jpeg
          caption: "KERNEL_NODE_0: Online. Benvenuto nel sistema."
