name: Kernel_Visual_Pulse
on: [push]

jobs:
  tele_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send Image Pulse
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          photo: logokernel.jpeg  # <--- ASSICURATI CHE IL NOME FILE SIA IDENTICO
          caption:
            ─── [ KERNEL_NODE_0 ] ───
            AUTHENTICATION: GRANTED
            STATUS: ONLINE
            
            Benvenuto nel cuore del sistema. 
            Qui la realtà viene patchata e 
            il destino riscritto. 
            
            > Sincronizzazione completata.
            > Resta in ascolto degli impulsi.

            Cluster: Root
