name: Kernel_Visual_Pulse
on: [push]

jobs:
  tele_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          photo: logokernel.jpeg
          parse_mode: ""
          caption: |
            ----[ KERNEL_NODE_0 ]----
            AUTHENTICATION: GRANTED
            STATUS: ONLINE

            Welcome to the system core.
            Synchronization complete.